{{ if kindIs "invalid" .Values.clusterautoscaler }}
{{ else }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cluster-autoscaler
  namespace: {{ .Values.global.namespace }}
  labels:
      prometheus: "kube-prometheus"
spec:
  selector:
    matchLabels:
      app: cluster-autoscaler
  endpoints:
  - port: http
    interval: 5s
  namespaceSelector:
    any: true
{{ end }}
