apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: cnvrg-gateway
  namespace: {{ .Values.global.namespace }}
  annotations:
    "helm.sh/hook": "pre-install"
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        {{ if kindIs "invalid" .Values.global.domain }}
        - {{ printf "*.%s.nip.io" .Values.ip | quote }}
        {{ else }}
        - {{ printf "*.%s" .Values.global.domain | quote }}
        {{ end }}
      tls:
        httpsRedirect: false
    - hosts:
        {{ if kindIs "invalid" .Values.global.domain }}
        - {{ printf "*.%s.nip.io" .Values.ip | quote }}
        {{ else }}
        - {{ printf "*.%s" .Values.global.domain | quote }}
        {{ end }}
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        mode: SIMPLE
        privateKey: /etc/istio/ingressgateway-certs/tls.key
        serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
