{{- if (.Values.enabled) }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: elastalert
  name: elastalert
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3030
  selector:
    app: elastalert
  type: ClusterIP
{{ end }}
