{{- if (.Values.enabled) }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: elastalert-vs
  namespace: {{ .Values.global.namespace }}
spec:
  gateways:
  - cnvrg-gateway
  hosts:
  {{ if kindIs "invalid" .Values.global.domain }}
  - {{ printf "*.elastalert.%s.nip.io" .Values.ip | quote }}
  {{ else }}
  - {{ printf "elastalert.%s" .Values.global.domain | quote }}
  {{ end }}
  http:
  - retries:
      attempts: 4
      perTryTimeout: 40s
    timeout: 80s
    route:
    - destination:
        host: elastalert.cnvrg.svc.cluster.local
{{ end }}
