apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: {{ .Values.global.namespace }}
  labels:
    k8s-app: kibana-logging
spec:
  ports:
  - port: 5601
    protocol: TCP
    targetPort: ui
  selector:
    k8s-app: kibana-logging
